### ISSUE TITLE
Cannot use proxy-pass

### ISSUE THREAD

**Issue by giovi321** [hedwiggggg/spotify-ripper-web#1]
Hi,
I cannot access to the interface through apache2 reverse proxy pass, I get no errors but i just see a blank page. Any idea why or how to debug this?
thanks!

**Comment by hedwiggggg** [comment]
woah man, no idea;
Can you write down a minimal instruction so i can reproduce this error?

**Comment by giovi321** [comment]
So I set up an Apache2 reverse proxy, as my spotify-ripper-web is running on a server and I access to it through a client. Basically any http request to the ip of the server is redirected to the ip:port of the spotify-ripper-web instance. However, I just see a blank page and no content at all

**Comment by giovi321** [comment]
@hedwiggggg any chance to change the base url of the webapp? I think this is the issue.

**Comment by hedwiggggg** [comment]
https://github.com/hedwiggggg/spotify-ripper-web/blob/master/spotify-ripper-web-backend/app.js#L64
https://github.com/hedwiggggg/spotify-ripper-web/blob/master/spotify-ripper-web-frontend/vue.config.js#L2

you mean this?

**Comment by hedwiggggg** [comment]
http://localhost:<your_port>/web/

It kinda sounds like you forgot to add the /web to your url

**Comment by giovi321** [comment]
So, quick update on this as you were very kind helping me :)
I wanted to run this on a virtual server and proxy it using apache2 proxy and proxy-pass.
I have been able to change the base uri of spotify-ripper-web (modifying the two files you pointed out), but I still couldn't figure out how to proxy the ws.
Bottom line, I just put a vpn on the virtual server and access to it through the vpn :)

**Comment by hedwiggggg** [comment]
yes it's possible by setting up a tcp rule for the ws port; but that's only theoretical, idk how it works with apache. But I guess there are a lot answers for that @google.
